service:
  name: image-resize

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

functions:
  resizeImage:
    handler: handler.process
    timeout: 30
    memorySize: 1024
    description: Resize Images
